version: '3.8'
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testpass
    ports:
      - "3307:3306"
  webserver:
    image: phpstorm/php-apache:7.4-xdebug2.9
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
